use std::time::Duration as StdDuration;

use chrono::{DateTime, SecondsFormat, Utc};

use crate::context::TelemetryContext;
use crate::contracts::*;
use crate::telemetry::{ContextTags, Measurements, Properties, Telemetry};
use crate::time::{self, Duration};
use crate::uuid::Uuid;

/// Represents the result of executing an availability test.
///
/// # Examples
/// ```rust, no_run
/// # use appinsights::TelemetryClient;
/// # let client = TelemetryClient::new("<instrumentation key>".to_string());
/// use appinsights::telemetry::{Telemetry, AvailabilityTelemetry};
/// use std::time::Duration;
///
/// // create a telemetry item
/// let mut telemetry = AvailabilityTelemetry::new(
///     "PING https://api.github.com/dmolokanov/appinsights-rs".to_string(),
///      Duration::from_secs(2),
///      true,
/// );
///
/// // attach custom properties, measurements and context tags
/// telemetry.properties_mut().insert("component".to_string(), "data_processor".to_string());
/// telemetry.tags_mut().insert("os_version".to_string(), "linux x86_64".to_string());
/// telemetry.measurements_mut().insert("body_size".to_string(), 115.0);
///
/// // submit telemetry item to server
/// client.track(telemetry);
/// ```
pub struct AvailabilityTelemetry {
    /// Identifier of a test run.
    /// It is used to correlate steps of test run and telemetry generated by the service.
    id: Option<Uuid>,

    /// Name of the test that this result represents.
    name: String,

    /// Duration of the test run.
    duration: Duration,

    /// Indication of successful or unsuccessful call.
    success: bool,

    /// The time stamp when this telemetry was measured.
    timestamp: DateTime<Utc>,

    /// Name of the location where the test was run.
    run_location: Option<String>,

    /// Diagnostic message for the result.
    message: Option<String>,

    /// Custom properties.
    properties: Properties,

    /// Telemetry context containing extra, optional tags.
    tags: ContextTags,

    /// Custom measurements.
    measurements: Measurements,
}

impl AvailabilityTelemetry {
    /// Creates a new availability telemetry item with the specified test name, duration and success code.
    pub fn new(name: String, duration: StdDuration, success: bool) -> Self {
        Self {
            id: Option::default(),
            name,
            duration: duration.into(),
            run_location: Option::default(),
            message: Option::default(),
            success,
            timestamp: time::now(),
            properties: Properties::default(),
            tags: ContextTags::default(),
            measurements: Measurements::default(),
        }
    }

    /// Returns custom measurements to submit with the telemetry item.
    pub fn measurements(&self) -> &Measurements {
        &self.measurements
    }

    /// Returns mutable reference to custom measurements.
    pub fn measurements_mut(&mut self) -> &mut Measurements {
        &mut self.measurements
    }
}

impl Telemetry for AvailabilityTelemetry {
    /// Returns the time when this telemetry was measured.
    fn timestamp(&self) -> DateTime<Utc> {
        self.timestamp
    }

    /// Returns custom properties to submit with the telemetry item.
    fn properties(&self) -> &Properties {
        &self.properties
    }

    /// Returns mutable reference to custom properties.
    fn properties_mut(&mut self) -> &mut Properties {
        &mut self.properties
    }

    /// Returns context data containing extra, optional tags. Overrides values found on client telemetry context.
    fn tags(&self) -> &ContextTags {
        &self.tags
    }

    /// Returns mutable reference to custom tags.
    fn tags_mut(&mut self) -> &mut ContextTags {
        &mut self.tags
    }
}

impl From<(TelemetryContext, AvailabilityTelemetry)> for Envelope {
    fn from((context, telemetry): (TelemetryContext, AvailabilityTelemetry)) -> Self {
        Envelope {
            name: "Microsoft.ApplicationInsights.Availability".into(),
            time: telemetry.timestamp.to_rfc3339_opts(SecondsFormat::Millis, true),
            i_key: Some(context.i_key),
            tags: Some(ContextTags::combine(context.tags, telemetry.tags).into()),
            data: Some(Base::Data(Data::AvailabilityData(AvailabilityData {
                id: telemetry
                    .id
                    .map(|id| id.to_hyphenated().to_string())
                    .unwrap_or_default(),
                name: telemetry.name,
                duration: telemetry.duration.to_string(),
                success: telemetry.success,
                run_location: telemetry.run_location,
                message: telemetry.message,
                properties: Some(Properties::combine(context.properties, telemetry.properties).into()),
                measurements: Some(telemetry.measurements.into()),
                ..AvailabilityData::default()
            }))),
            ..Envelope::default()
        }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use chrono::TimeZone;

    use super::*;

    #[test]
    fn it_overrides_properties_from_context() {
        time::set(Utc.ymd(2019, 1, 2).and_hms_milli(3, 4, 5, 800));

        let mut context = TelemetryContext::new("instrumentation".into());
        context.properties_mut().insert("test".into(), "ok".into());
        context.properties_mut().insert("no-write".into(), "fail".into());

        let mut telemetry = AvailabilityTelemetry::new(
            "GET https://example.com/main.html".into(),
            StdDuration::from_secs(2),
            true,
        );
        telemetry.properties_mut().insert("no-write".into(), "ok".into());
        telemetry.measurements_mut().insert("latency".into(), 200.0);

        let envelop = Envelope::from((context, telemetry));

        let expected = Envelope {
            name: "Microsoft.ApplicationInsights.Availability".into(),
            time: "2019-01-02T03:04:05.800Z".into(),
            i_key: Some("instrumentation".into()),
            tags: Some(BTreeMap::default()),
            data: Some(Base::Data(Data::AvailabilityData(AvailabilityData {
                name: "GET https://example.com/main.html".into(),
                duration: "0.00:00:02.0000000".into(),
                success: true,
                message: None,
                properties: Some({
                    let mut properties = BTreeMap::default();
                    properties.insert("test".into(), "ok".into());
                    properties.insert("no-write".into(), "ok".into());
                    properties
                }),
                measurements: Some({
                    let mut measurement = BTreeMap::default();
                    measurement.insert("latency".into(), 200.0);
                    measurement
                }),
                ..AvailabilityData::default()
            }))),
            ..Envelope::default()
        };

        assert_eq!(envelop, expected)
    }

    #[test]
    fn it_overrides_tags_from_context() {
        time::set(Utc.ymd(2019, 1, 2).and_hms_milli(3, 4, 5, 700));

        let mut context = TelemetryContext::new("instrumentation".into());
        context.tags_mut().insert("test".into(), "ok".into());
        context.tags_mut().insert("no-write".into(), "fail".into());

        let mut telemetry = AvailabilityTelemetry::new(
            "GET https://example.com/main.html".into(),
            StdDuration::from_secs(2),
            true,
        );
        telemetry.tags_mut().insert("no-write".into(), "ok".into());

        let envelop = Envelope::from((context, telemetry));
        let expected = Envelope {
            name: "Microsoft.ApplicationInsights.Availability".into(),
            time: "2019-01-02T03:04:05.700Z".into(),
            i_key: Some("instrumentation".into()),
            tags: Some({
                let mut tags = BTreeMap::default();
                tags.insert("test".into(), "ok".into());
                tags.insert("no-write".into(), "ok".into());
                tags
            }),
            data: Some(Base::Data(Data::AvailabilityData(AvailabilityData {
                name: "GET https://example.com/main.html".into(),
                duration: "0.00:00:02.0000000".into(),
                success: true,
                message: None,
                properties: Some(BTreeMap::default()),
                measurements: Some(BTreeMap::default()),
                ..AvailabilityData::default()
            }))),
            ..Envelope::default()
        };

        assert_eq!(envelop, expected)
    }
}
