# .kodiak.toml
version = 1

[approve]
auto_approve_usernames = ["dependabot-preview"]

[merge]
method = "squash" # default: "merge"
delete_branch_on_merge = true # default: false

[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"
strip_html_comments = true # default: false
